msvc: Don't check for the mingw version when building using msvc

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2505,9 +2505,12 @@ case $target_os in
         dlltool="${cross_prefix}dlltool"
         enable dos_paths
         check_cflags -fno-common
-        check_cpp_condition _mingw.h "defined (__MINGW64_VERSION_MAJOR) || (__MINGW32_MAJOR_VERSION > 3) \
-                                      || (__MINGW32_MAJOR_VERSION == 3 && __MINGW32_MINOR_VERSION >= 15)" ||
-                die "ERROR: MinGW runtime version must be >= 3.15."
+        if test $cc_type != msvc; then
+            echo CC: $cc_type, $cc_version, $cc_ident
+            check_cpp_condition _mingw.h "defined (__MINGW64_VERSION_MAJOR) || (__MINGW32_MAJOR_VERSION > 3) \
+                                       || (__MINGW32_MAJOR_VERSION == 3 && __MINGW32_MINOR_VERSION >= 15)" ||
+                 die "ERROR: MinGW runtime version must be >= 3.15."
+        fi
         add_cppflags -U__STRICT_ANSI__
         ;;
     cygwin*)
